DROP TABLE zgloszenie CASCADE CONSTRAINTS;
DROP TABLE zglaszajacy CASCADE CONSTRAINTS;
DROP TABLE dyspozytor CASCADE CONSTRAINTS;
DROP TABLE strazak CASCADE CONSTRAINTS;
Drop TABLE pojazd CASCADE CONSTRAINTS;
DROP TABLE jednostka CASCADE CONSTRAINTS;
DROP TABLE akcja CASCADE CONSTRAINTS;