/*DROP DATABASE straz;*/

DROP TABLE zgloszenie CASCADE CONSTRAINTS;
DROP TABLE zglaszajacy CASCADE CONSTRAINTS;
DROP TABLE dyspozytor CASCADE CONSTRAINTS;
DROP TABLE zarobki CASCADE CONSTRAINTS;
DROP TABLE badanie CASCADE CONSTRAINTS;
DROP TABLE strazak CASCADE CONSTRAINTS;
DROP TABLE badanie_techniczne CASCADE CONSTRAINTS;
Drop TABLE pojazd CASCADE CONSTRAINTS;
DROP TABLE jednostka CASCADE CONSTRAINTS;
DROP TABLE akcja CASCADE CONSTRAINTS;


